@startuml
title Ієрархічне дерево \nіз вкладеними вузлами

node "Користувач\n(ім’я, вік, алергії, ціль)" {
  node "ДаніПроЗдоров’я\n(вага, зріст, ІМТ, активність, обмеження)" {
    node "Рекомендації\n(обсяг_води, фізична_активність)"
  }
  node "ПланХарчування\n(сніданок, обід, вечеря, калорійність)"
  node "Досягнення\n(тренування, вправи, нагороди)"
  node "Самоповага\n(рівень, впевненість)"
  node "ТанцювальніПодії\n(назва, тип, дата, місце)"
}

@enduml
