-- Видалення старого користувача
DROP USER software_dev CASCADE;

-- Створення нового користувача
CREATE USER software_dev IDENTIFIED BY devpass;

-- Надання прав
GRANT CONNECT, RESOURCE, CREATE SESSION TO software_dev;
ALTER USER software_dev QUOTA UNLIMITED ON USERS;

-- Підключення до схеми software_dev
CONNECT software_dev/devpass@localhost:1521/XEPDB1

-- Створення таблиці
CREATE TABLE PLAN_HARCHUVANNIA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    snidanok VARCHAR2(100),
    obed VARCHAR2(100),
    vecheria VARCHAR2(100),
    kaloriynist NUMBER
);

-- Вставка тестових даних
INSERT INTO PLAN_HARCHUVANNIA (snidanok, obed, vecheria, kaloriynist)
VALUES ('Yaytsia', 'Kurka', 'Ryba', 2000);

COMMIT;
EXIT;
